# Generated by Django 5.0 on 2023-12-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phome', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
    ]
