# Generated by Django 5.0 on 2023-12-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerdetails',
            old_name='phome',
            new_name='phone',
        ),
    ]
