# Generated by Django 5.0 on 2023-12-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_phome_ownerdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='owner'),
        ),
    ]
