# Generated by Django 5.0 on 2023-12-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_ownerdetails_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=70)),
                ('service_description', models.TextField()),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
    ]
