# Generated by Django 5.0 on 2023-12-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.CharField(max_length=40)),
                ('project_subCategory', models.CharField(max_length=40)),
                ('company_name', models.CharField(max_length=40)),
                ('details', models.TextField()),
                ('project_image', models.ImageField(upload_to='featured_project')),
                ('project_url', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CliantTestimonails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliant_name', models.CharField(max_length=40)),
                ('testimonials', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.featuredprojects')),
            ],
        ),
    ]
