# Generated by Django 5.0 on 2023-12-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_featuredprojects_clianttestimonails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessonalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_level', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_level', models.IntegerField(max_length=100)),
            ],
        ),
    ]
