# Generated by Django 5.0 on 2023-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_professonalskills_technicalskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=30)),
                ('institute_name', models.CharField(max_length=50)),
                ('course_start_year', models.IntegerField()),
                ('course_ending_year', models.IntegerField()),
                ('about_degree', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expirence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=50)),
                ('job_joining_year', models.IntegerField()),
                ('job_ending_year', models.IntegerField()),
                ('role_ot_post', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='professonalskills',
            name='skill_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='technicalskills',
            name='skill_level',
            field=models.IntegerField(),
        ),
    ]
