# Generated by Django 5.0 on 2023-12-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_pricing_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='icon',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
