# Generated by Django 5.0 on 2023-12-14 19:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_cliantmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', ckeditor.fields.RichTextField()),
                ('cv', models.FileField(upload_to='cv')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
