# Generated by Django 5.0 on 2023-12-14 19:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_company', models.CharField(max_length=50)),
                ('rewiew', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='clients')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
