# Generated by Django 5.0 on 2023-12-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_clientreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='teammates')),
            ],
        ),
    ]
